[general]
interface = "enp14s0" 
ipStart = "192.168.100.58" 
ipEnd = "192.168.100.69"  


[devices]
[devices.coffee]
id = "coffee"
action = "coffeeAction"
broker = "tcp://192.168.100.11:1883"

[devices.coffee2]
id = "coffee2"
action = "coffeeAction"
broker = "tcp://192.168.100.11:1883"

[devices.coffee3]
id = "coffee3"
action = "coffeeAction"
broker = "tcp://192.168.100.11:1883"