[general]
  id = "37e0b5f4-a3ff-427c-bdd9-1460c2c8138a"
  interface = "enp14s0"

[devices]
  [devices.coffee]
    id = "coffee"
    action = "coffeeAction"
    broker = "tcp://0.0.0.0:1883"
  [devices.coffee2]
    id = "coffee2"
    action = "coffeeAction"
    broker = "tcp://0.0.0.0:1883"
  [devices.coffee3]
    id = "coffee3"
    action = "coffeeAction"
    broker = "tcp://0.0.0.0:1883"
