[general]
interface = "enp14s0" 
#Subnet mask will be /24 
#So by default there are 254 possible ip's under one subnet
ipStart = "192.168.100.58" 
ipEnd = "192.168.100.59"  


[devices]
[devices.coffee]
id = "coffee"
action = "coffeeAction"
broker = "tcp://192.168.100.11:1883"

[devices.coffee2]
id = "coffee2"
action = "coffeeAction"
broker = "tcp://192.168.100.11:1883"

[devices.coffee3]
id = "coffee3"
action = "coffeeAction"
broker = "tcp://192.168.100.11:1883"